"""release error column

Revision ID: 82a0b67c74f7
Revises: a0f7c92eda3d
Create Date: 2026-07-11 11:13:19.668844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '82a0b67c74f7'
down_revision: Union[str, None] = 'a0f7c92eda3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('release', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('release', schema=None) as batch_op:
        batch_op.drop_column('error')

    # ### end Alembic commands ###
