"""user_book id and pending push

Revision ID: a0f7c92eda3d
Revises: eb8999543631
Create Date: 2026-07-11 10:46:35.847218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a0f7c92eda3d'
down_revision: Union[str, None] = 'eb8999543631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hardcover_user_book_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pending_push', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('pending_push')
        batch_op.drop_column('hardcover_user_book_id')

    # ### end Alembic commands ###
