"""audio files and media progress

Revision ID: f1a12fb43179
Revises: 82a0b67c74f7
Create Date: 2026-07-11 19:43:34.779484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f1a12fb43179'
down_revision: Union[str, None] = '82a0b67c74f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('rel_path', sa.Text(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('mtime_ms', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('chapters_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audio_file', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audio_file_book_id'), ['book_id'], unique=False)

    op.create_table('media_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('current_time', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('is_finished', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_progress_book_id'), ['book_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_progress_book_id'))

    op.drop_table('media_progress')
    with op.batch_alter_table('audio_file', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audio_file_book_id'))

    op.drop_table('audio_file')
    # ### end Alembic commands ###
